name: Deploy Wedding App Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # CORRECTED: Use the v2 action
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push processImage to ECR
        env:
          # This is the registry URI provided by the login step
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          
          # This is just the repository NAME from your secrets
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          
          # This is the unique, immutable tag based on your git commit
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Here we construct the full, correct URI from the pieces
          docker build --target processImage -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy with Serverless Framework
        run: |
          npm install -g serverless
          # We will need to update serverless.yml to use this new image tag
          # For now, this will deploy the service definition
          serverless deploy --stage dev