name: Deploy Wedding App Backend

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push processImage to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # --- START DEBUGGING BLOCK ---
          echo "AWS Region from secrets: ${{ secrets.AWS_REGION }}"
          echo "ECR Registry from login step: $ECR_REGISTRY"
          echo "ECR Repository from secrets: '$ECR_REPOSITORY'" # The quotes are important to see whitespace
          echo "Image Tag from GitHub SHA: $IMAGE_TAG"
          echo "Full Image URI being built: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          # --- END DEBUGGING BLOCK ---
          
          docker build --target processImage -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy with Serverless Framework
        run: |
          npm install -g serverless
          serverless deploy --stage dev
